v1

diff --git a/tests/main/cgroup-freezer/task.yaml b/tests/main/cgroup-freezer/task.yaml
--- a/tests/main/cgroup-freezer/task.yaml
+++ b/tests/main/cgroup-freezer/task.yaml
@@ -1,52 +1,42 @@
 summary: Each snap process is moved to appropriate freezer cgroup
-# fedora-31: uses cgroupv2, which does not support a separate freezer controller
-systems: [ -fedora-31-*]
-
 details: |
     This test creates a snap process that suspends itself and ensures that it
     placed into the appropriate hierarchy under the freezer cgroup.
-
 prepare: |
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB"/snaps.sh
+    . $TESTSLIB/snaps.sh
     install_local test-snapd-sh
-
-restore: |
-    rmdir /sys/fs/cgroup/freezer/snap.test-snapd-sh || true
-
 execute: |
-    trap 'killall test-snapd-sh || true' EXIT
     # Start a "sleep" process in the background
-    #shellcheck disable=SC2016
-    test-snapd-sh.sh -c 'touch $SNAP_DATA/1.stamp && exec sleep 1h' &
+    test-snapd-sh -c 'touch $SNAP_DATA/1.stamp && exec sleep 1h' &
     pid1=$!
     # Ensure that snap-confine has finished its task and that the snap process
     # is active. Note that we don't want to wait forever either.
-    for _ in $(seq 30); do
+    for i in $(seq 30); do
         test -e /var/snap/test-snapd-sh/current/1.stamp && break
         sleep 0.1
     done
     # While the process is alive its PID can be seen in the tasks file of the
     # control group.
-    MATCH "$pid1" < /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks
+    cat /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks | MATCH "$pid1"
 
     # Start a second process so that we can check adding tasks to an existing
     # control group.
-    #shellcheck disable=SC2016
-    test-snapd-sh.sh -c 'touch $SNAP_DATA/2.stamp && exec sleep 1h' &
+    test-snapd-sh -c 'touch $SNAP_DATA/2.stamp && exec sleep 1h' &
     pid2=$!
-    for _ in $(seq 30); do
+    for i in $(seq 30); do
         test -e /var/snap/test-snapd-sh/current/2.stamp && break
         sleep 0.1
     done
-    MATCH "$pid2" < /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks
+    cat /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks | MATCH "$pid2"
 
     # When the process terminates the control group is updated and the task no
     # longer registers there.
     kill "$pid1"
-    wait "$pid1" || true  # wait returns the exit code and we kill the process
-    MATCH -v "$pid1" < /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks
+    wait -n || true  # wait returns the exit code and we kill the process
+    cat /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks | MATCH -v "$pid1"
 
     kill "$pid2"
-    wait "$pid2" || true  # same as above
-    MATCH -v "$pid2" < /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks
+    wait -n || true  # same as above
+    cat /sys/fs/cgroup/freezer/snap.test-snapd-sh/tasks | MATCH -v "$pid2"
+restore: |
+    rmdir /sys/fs/cgroup/freezer/snap.test-snapd-sh || true
diff --git a/tests/main/interfaces-avahi-observe/task.yaml b/tests/main/interfaces-avahi-observe/task.yaml
--- a/tests/main/interfaces-avahi-observe/task.yaml
+++ b/tests/main/interfaces-avahi-observe/task.yaml
@@ -1,14 +1,15 @@
 summary: check that avahi-observe interface works
 
-systems: [-ubuntu-core-*, -fedora-*, -opensuse-*, -arch-*, -amazon-*, -centos-*]
+systems: [-ubuntu-core-*, -fedora-*, -opensuse-*]
 
 prepare: |
     echo "Given a snap with an avahi-observe interface plug is installed"
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB"/snaps.sh
+    . $TESTSLIB/snaps.sh
     install_generic_consumer avahi-observe,unity7
 
-    echo "And avahi-daemon is configured"
+    echo "And avahi-daemon is installed and configured"
+    . $TESTSLIB/pkgdb.sh
+    distro_install_package avahi-daemon
     sed -i 's/^#enable-dbus=yes/enable-dbus=yes/' /etc/avahi/avahi-daemon.conf
     if [[ "$SPREAD_SYSTEM" = ubuntu-14.04-* ]]; then
         initctl reload-configuration
@@ -18,31 +19,34 @@ prepare: |
         systemctl restart avahi-daemon.{socket,service}
     fi
 
+restore: |
+    rm -f *.error
+    . $TESTSLIB/pkgdb.sh
+    distro_purge_package avahi-daemon
+    distro_auto_remove_packages
+
 execute: |
-    avahi_dbus_call() {
-        generic-consumer.cmd dbus-send --system --print-reply --dest=org.freedesktop.Avahi / org.freedesktop.Avahi.Server.GetHostName
-    }
+    CONNECTED_PATTERN=":avahi-observe +generic-consumer"
+    DISCONNECTED_PATTERN="^\- +generic-consumer:avahi-observe"
+
+    avahi_dbus_call="dbus-send --system --print-reply --dest=org.freedesktop.Avahi / org.freedesktop.Avahi.Server.GetHostName"
 
     echo "Then the plug is disconnected by default"
-    snap interfaces -i avahi-observe | MATCH '^\- +generic-consumer:avahi-observe'
+    snap interfaces | MATCH "$DISCONNECTED_PATTERN"
+
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "And the snap is not able to access avahi provided info"
+        if generic-consumer.cmd $avahi_dbus_call 2>avahi.error; then
+            echo "Expected error with disconnected plug didn't happen"
+            exit 1
+        fi
+        MATCH "org.freedesktop.DBus.Error.AccessDenied" < avahi.error
+    fi
 
     echo "When the plug is connected"
     snap connect generic-consumer:avahi-observe
+    snap interfaces | MATCH "$CONNECTED_PATTERN"
 
     echo "Then the snap is able to access avahi provided info"
-    hostname=$(hostname)
-    avahi_dbus_call | MATCH "$hostname"
-
-    if [ "$(snap debug confinement)" = partial ]; then
-        exit 0
-    fi
-
-    echo "When the plug is disconnected"
-    snap disconnect generic-consumer:avahi-observe
-
-    echo "And the snap is not able to access avahi provided info"
-    if avahi_dbus_call 2> avahi.error; then
-        echo "Expected error with disconnected plug didn't happen"
-        exit 1
-    fi
-    MATCH "org.freedesktop.DBus.Error.AccessDenied" < avahi.error
+    hostname=$(cat /etc/hostname)
+    generic-consumer.cmd $avahi_dbus_call | MATCH "$hostname"
diff --git a/tests/main/interfaces-browser-support/task.yaml b/tests/main/interfaces-browser-support/task.yaml
--- a/tests/main/interfaces-browser-support/task.yaml
+++ b/tests/main/interfaces-browser-support/task.yaml
@@ -34,32 +34,33 @@ prepare: |
     echo "Given a snap declaring a plug on browser-support with allow-sandbox set to $ALLOW_SANDBOX is installed"
     cp -ar "$TESTSLIB/snaps/browser-support-consumer" .
     sed "s/@ALLOW_SANDBOX@/$ALLOW_SANDBOX/" browser-support-consumer/meta/snap.yaml.in > browser-support-consumer/meta/snap.yaml
-    chmod 644 browser-support-consumer/meta/snap.yaml
     snap pack browser-support-consumer browser-support-consumer
     snap install --dangerous browser-support-consumer/*.snap
     rm -rf browser-support-consumer
 
 restore: |
-    rm -f /var/tmp/test
+    rm -f *.error /var/tmp/test
     for file in $OWNED_FILES $READABLE_FILES $READABLE_WITH_SANDBOX_FILES; do
-        rm -f "$file"
+        rm -f $file
     done
 
-    while read -r dir; do
-        rm -rf "$dir"
-    done < created_dirs
+    for dir in $(cat created_dirs); do
+        rm -rf $dir
+    done
     rm -f created_dirs
 
 execute: |
-    #shellcheck source=tests/lib/dirs.sh
     . "$TESTSLIB/dirs.sh"
+
+    CONNECTED_PATTERN=":browser-support +browser-support-consumer"
+    DISCONNECTED_PATTERN="^\- +browser-support-consumer:browser-support"
 
     if [ "$ALLOW_SANDBOX" = "false" ]; then
        echo "If allow-sandbox is false then the plug is connected by default"
+       snap interfaces | MATCH "$CONNECTED_PATTERN"
     else
        echo "If allow-sandbox is true then the plug is not connected by default"
-       snap interfaces -i browser-support | MATCH '\- +browser-support-consumer:browser-support'
-
+       ! snap interfaces | MATCH "$CONNECTED_PATTERN"
        echo "Do connect it manually"
        snap connect browser-support-consumer:browser-support
     fi
@@ -78,9 +79,9 @@ execute: |
 
     echo "And the snap is able to access readable files"
     for readable_file in $READABLE_FILES; do
-        parent_dir=$(dirname "$readable_file")
-        if [ ! -d "$parent_dir" ]; then
-            if mkdir -p "$parent_dir"; then
+        parent_dir=$(dirname $readable_file)
+        if [ ! -d $parent_dir ]; then
+            if mkdir -p $parent_dir; then
                 echo "$parent_dir" >> created_dirs
             else
                 echo "$parent_dir couldn't be created, write-only partition?"
@@ -92,9 +93,9 @@ execute: |
     done
 
     for readable_file in $READABLE_WITH_SANDBOX_FILES; do
-        parent_dir=$(dirname "$readable_file")
-        if [ ! -d "$parent_dir" ]; then
-            mkdir -p "$parent_dir"
+        parent_dir=$(dirname $readable_file)
+        if [ ! -d $parent_dir ]; then
+            mkdir -p $parent_dir
             echo "$parent_dir" >> created_dirs
         fi
         echo "test" > "$readable_file"
@@ -106,65 +107,55 @@ execute: |
         done
     fi
 
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "And the resources available with sandbox are not reachable without it"
+        if [ "$ALLOW_SANDBOX" = "false" ]; then
+            for readable_file in $READABLE_WITH_SANDBOX_FILES; do
+                if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file 2>${PWD}/readable-without-sandbox-read.err" test; then
+                    echo "Expected error without sandbox didn't happen"
+                    exit 1
+                fi
+                MATCH "Permission denied" < readable-without-sandbox-read.err
+            done
+        fi
 
-    if [ "$ALLOW_SANDBOX" = "false" ]; then
-        echo "And the policy has the ptrace suppression rule without sandbox"
-        MATCH '^deny ptrace \(trace\),' < /var/lib/snapd/apparmor/profiles/snap.browser-support-consumer.cmd
-    else
-        echo "And the policy has the ptrace suppression rule with sandbox"
-        MATCH '^deny ptrace \(trace\),' < /var/lib/snapd/apparmor/profiles/snap.browser-support-consumer.cmd && echo "Found ptrace rule, but shouldn't have" && exit 1
-    fi
+        echo "When the plug is disconnected"
+        snap disconnect browser-support-consumer:browser-support
+        snap interfaces | MATCH "$DISCONNECTED_PATTERN"
 
-    echo "And the resources available with sandbox are not reachable without it"
-    if [ "$ALLOW_SANDBOX" = "false" ]; then
-        for readable_file in $READABLE_WITH_SANDBOX_FILES; do
-            if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file" test 2> readable-without-sandbox-read.err; then
-                echo "Expected error without sandbox didn't happen"
-                exit 1
-            fi
-            MATCH "Permission denied" < readable-without-sandbox-read.err
-        done
-    fi
-
-    echo "When the plug is disconnected"
-    snap disconnect browser-support-consumer:browser-support
-
-    echo "Then the snap is not able to access tmp"
-    if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd ls /var/tmp/" test 2> tmpdir-access.err; then
-        echo "Expected error with disconnected plug didn't happen"
-        exit 1
-    fi
-    MATCH "Permission denied" < tmpdir-access.err
-    if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat /var/tmp/etilqs_test" test 2> tmpfile-read.err; then
-        echo "Expected error with disconnected plug didn't happen"
-        exit 1
-    fi
-    MATCH "Permission denied" < tmpfile-read.err
-
-    for owned_file in $OWNED_FILES; do
-        if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $owned_file" test 2> owned-read.err; then
+        echo "Then the snap is not able to access tmp"
+        if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd ls /var/tmp/ 2>${PWD}/tmpdir-access.err" test; then
             echo "Expected error with disconnected plug didn't happen"
             exit 1
         fi
-        MATCH "Permission denied" < owned-read.err
-    done
-    for readable_file in $READABLE_FILES; do
-        if [ -f "$readable_file" ] && su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file" test 2> readable-read.err; then
+        MATCH "Permission denied" < tmpdir-access.err
+        if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat /var/tmp/etilqs_test 2>${PWD}/tmpfile-read.err" test; then
             echo "Expected error with disconnected plug didn't happen"
             exit 1
         fi
-        MATCH "Permission denied" < readable-read.err
-    done
-    if [ "$ALLOW_SANDBOX" = "true" ]; then
-        for readable_file in $READABLE_WITH_SANDBOX_FILES; do
-            if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file" test 2> readable-with-sandbox-read.err; then
+        MATCH "Permission denied" < tmpfile-read.err
+
+        for owned_file in $OWNED_FILES; do
+            if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $owned_file 2>${PWD}/owned-read.err" test; then
                 echo "Expected error with disconnected plug didn't happen"
                 exit 1
             fi
-            MATCH "Permission denied" < readable-with-sandbox-read.err
+            MATCH "Permission denied" < owned-read.err
         done
+        for readable_file in $READABLE_FILES; do
+            if [ -f "$readable_file" ] && su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file 2>${PWD}/readable-read.err" test; then
+                echo "Expected error with disconnected plug didn't happen"
+                exit 1
+            fi
+            MATCH "Permission denied" < readable-read.err
+        done
+        if [ "$ALLOW_SANDBOX" = "true" ]; then
+            for readable_file in $READABLE_WITH_SANDBOX_FILES; do
+                if su -l -c "$SNAP_MOUNT_DIR/bin/browser-support-consumer.cmd cat $readable_file 2>${PWD}/readable-with-sandbox-read.err" test; then
+                    echo "Expected error with disconnected plug didn't happen"
+                    exit 1
+                fi
+                MATCH "Permission denied" < readable-with-sandbox-read.err
+            done
+        fi
     fi
-
diff --git a/tests/main/interfaces-locale-control/task.yaml b/tests/main/interfaces-locale-control/task.yaml
--- a/tests/main/interfaces-locale-control/task.yaml
+++ b/tests/main/interfaces-locale-control/task.yaml
@@ -1,6 +1,6 @@
 summary: Ensure that the locale-control interface works.
 
-systems: [-fedora-*, -opensuse-*, -arch-*, -amazon-*, -centos-*]
+systems: [-fedora-*, -opensuse-*]
 
 summary: |
     The locale-control interface allows a snap to access the locale configuration.
@@ -22,12 +22,9 @@ prepare: |
         fi
     fi
 
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB/snaps.sh"
-
     echo "Given a snap declaring a plug on the locale-control interface is installed"
-    install_local locale-control-consumer
-
+    snap pack $TESTSLIB/snaps/locale-control-consumer
+    snap install --dangerous locale-control-consumer_1.0_all.snap
     mv /etc/default/locale locale.back
     cat > /etc/default/locale <<EOF
     LANG="$LANG"
@@ -44,6 +41,7 @@ restore: |
         fi
     fi
 
+    rm -f locale-control-consumer_1.0_all.snap locale-read.error locale-write.error
     mv locale.back /etc/default/locale
 
 execute: |
@@ -56,8 +54,13 @@ execute: |
         fi
     fi
 
-    echo "The interface is not connected by default"
-    snap interfaces -i locale-control | MATCH '^- +locale-control-consumer:locale-control'
+    CONNECTED_PATTERN=":locale-control +locale-control-consumer"
+    DISCONNECTED_PATTERN="(?s).*?\n- +locale-control-consumer:locale-control"
+
+    echo "Then it is not connected by default"
+    snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+    echo "==================================="
 
     echo "When the plug is connected"
     snap connect locale-control-consumer:locale-control
@@ -65,16 +68,20 @@ execute: |
     echo "Then the snap is able to read the locale configuration"
     [ "$(su -l -c 'locale-control-consumer.get LANG' test)" = "$LANG" ]
 
+    echo "==================================="
+
     if [ "$(snap debug confinement)" = strict ] ; then
         echo "When the plug is disconnected"
         snap disconnect locale-control-consumer:locale-control
 
         echo "Then the snap is not able to read the locale configuration"
-        if su -l -c "locale-control-consumer.get LANG" test 2> locale-read.error; then
+        if su -l -c "locale-control-consumer.get LANG 2>${PWD}/locale-read.error" test; then
             echo "Expected permission error accessing locale configuration with disconnected plug"
             exit 1
         fi
         grep -q "Permission denied" locale-read.error
+
+        echo "==================================="
     fi
 
     echo "When the plug is connected"
@@ -84,16 +91,16 @@ execute: |
     locale-control-consumer.set LANG mylang
     grep -q "LANG=\"mylang\"" /etc/default/locale
 
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "==================================="
 
-    echo "When the plug is disconnected"
-    snap disconnect locale-control-consumer:locale-control
+        echo "When the plug is disconnected"
+        snap disconnect locale-control-consumer:locale-control
 
-    echo "Then the snap is not able to read the locale configuration"
-    if locale-control-consumer.set LANG mysecondlang 2> locale-write.error; then
-        echo "Expected permission error accessing locale configuration with disconnected plug"
-        exit 1
+        echo "Then the snap is not able to read the locale configuration"
+        if locale-control-consumer.set LANG mysecondlang 2>${PWD}/locale-write.error; then
+            echo "Expected permission error accessing locale configuration with disconnected plug"
+            exit 1
+        fi
+        grep -q "Permission denied" locale-write.error
     fi
-    grep -q "Permission denied" locale-write.error
diff --git a/tests/main/interfaces-mount-observe/task.yaml b/tests/main/interfaces-mount-observe/task.yaml
--- a/tests/main/interfaces-mount-observe/task.yaml
+++ b/tests/main/interfaces-mount-observe/task.yaml
@@ -12,47 +12,56 @@ details: |
     is also shown when the plug is connected.
 
 prepare: |
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB/snaps.sh"
-
     echo "Given a snap declaring a plug on the mount-observe interface is installed"
-    install_local mount-observe-consumer
+    snap pack $TESTSLIB/snaps/mount-observe-consumer
+    snap install --dangerous mount-observe-consumer_1.0_all.snap
+
+restore: |
+    rm -f mount-observe-consumer_1.0_all.snap
 
 execute: |
-    #shellcheck source=tests/lib/dirs.sh
-    . "$TESTSLIB"/dirs.sh
+    . $TESTSLIB/dirs.sh
 
-    echo "The interface is not connected by default"
-    snap interfaces -i mount-observe | MATCH -- '- +mount-observe-consumer:mount-observe'
+    CONNECTED_PATTERN=":mount-observe +mount-observe-consumer"
+    DISCONNECTED_PATTERN="(?s).*?\n- +mount-observe-consumer:mount-observe"
+
+    echo "Then the plug is shown as disconnected"
+    snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+    echo "========================================="
 
     echo "When the plug is connected"
     snap connect mount-observe-consumer:mount-observe
+    snap interfaces | grep -Pzq "$CONNECTED_PATTERN"
 
     echo "Then the mount info is reachable"
     expected="$SNAP_MOUNT_DIR/mount-observe-consumer"
     su -l -c "mount-observe-consumer" test | grep -Pq "$expected"
 
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "========================================="
+
+        echo "When the plug is disconnected"
+        snap disconnect mount-observe-consumer:mount-observe
+        snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+        echo "Then the mount info is not reachable"
+        if su -l -c "mount-observe-consumer" test; then
+            echo "Expected error accessing mount info with disconnected plug"
+            exit 1
+        fi
+    fi
+
+    echo "========================================="
+
     echo "When the plug is connected"
     snap connect mount-observe-consumer:mount-observe
+    snap interfaces | grep -Pzq "$CONNECTED_PATTERN"
 
     echo "And a new mount is created"
-    #shellcheck source=tests/lib/snaps.sh
     . "$TESTSLIB/snaps.sh"
-    install_local test-snapd-sh
+    install_local test-snapd-tools
 
     echo "Then the new mount info is reachable"
-    expected="$SNAP_MOUNT_DIR/test-snapd-sh"
+    expected="$SNAP_MOUNT_DIR/test-snapd-tools"
     su -l -c "mount-observe-consumer" test | grep -Pq "$expected"
-
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
-
-    echo "When the plug is disconnected"
-    snap disconnect mount-observe-consumer:mount-observe
-
-    echo "Then the mount info is not reachable"
-    if su -l -c "mount-observe-consumer" test; then
-        echo "Expected error accessing mount info with disconnected plug"
-        exit 1
-    fi
diff --git a/tests/main/interfaces-network-observe/task.yaml b/tests/main/interfaces-network-observe/task.yaml
--- a/tests/main/interfaces-network-observe/task.yaml
+++ b/tests/main/interfaces-network-observe/task.yaml
@@ -18,46 +18,51 @@ environment:
     SERVICE_NAME: "test-service"
 
 prepare: |
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB/snaps.sh"
-    #shellcheck source=tests/lib/systemd.sh
     . "$TESTSLIB/systemd.sh"
 
     echo "Given a snap declaring a plug on the network-observe interface is installed"
-    install_local network-observe-consumer
+    snap pack $TESTSLIB/snaps/network-observe-consumer
+    snap install --dangerous network-observe-consumer_1.0_all.snap
 
     echo "And a network service is up"
-    # shellcheck source=tests/lib/network.sh
-    . "$TESTSLIB"/network.sh
-    make_network_service "$SERVICE_NAME" "$SERVICE_FILE" "$PORT"
+    printf "#!/bin/sh -e\nwhile true; do echo \"HTTP/1.1 200 OK\n\nok\n\" |  nc -l -p $PORT; done" > $SERVICE_FILE
+    chmod a+x $SERVICE_FILE
+    systemd_create_and_start_unit $SERVICE_NAME "$(readlink -f $SERVICE_FILE)"
+
+    while ! netstat -lnt | grep -Pq "tcp.*?:$PORT +.*?LISTEN\n*"; do sleep 0.5; done
 
 restore: |
-    #shellcheck source=tests/lib/systemd.sh
     . "$TESTSLIB/systemd.sh"
 
-    #shellcheck disable=SC2153
-    systemd_stop_and_destroy_unit "$SERVICE_NAME"
+    systemd_stop_and_destroy_unit $SERVICE_NAME
+    rm -f network-observe-consumer_1.0_all.snap net-query.output $SERVICE_FILE
 
 execute: |
-    echo "The interface is disconnected by default"
-    snap interfaces -i network-observe | MATCH -- '^- +network-observe-consumer:network-observe'
+    CONNECTED_PATTERN=":network-observe +network-observe-consumer"
+    DISCONNECTED_PATTERN="(?s).*?\n- +network-observe-consumer:network-observe"
+
+    echo "Then the plug disconnected by default"
+    snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+    echo "===================================="
 
     echo "When the plug is connected"
     snap connect network-observe-consumer:network-observe
+    snap interfaces | grep -Pzq "$CONNECTED_PATTERN"
 
     echo "Then the snap command can query network status information"
-    network-observe-consumer | MATCH "LISTEN.*:$PORT"
+    network-observe-consumer | grep -P "0.0.0.0:$PORT.*?LISTEN"
 
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "===================================="
+
+        echo "When the plug is disconnected"
+        snap disconnect network-observe-consumer:network-observe
+        snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+        echo "Then the snap command can not query network status information"
+        if network-observe-consumer 2>net-query.output; then
+            echo "Expected error caling command with disconnected plug"
+        fi
+        cat net-query.output | grep -Pq "Permission denied"
     fi
-
-    echo "When the plug is disconnected"
-    snap disconnect network-observe-consumer:network-observe
-
-    echo "Then the snap command can not query network status information"
-    if network-observe-consumer 2> net-query.output; then
-        echo "Expected error caling command with disconnected plug"
-    fi
-    grep -Pq "Permission denied" < net-query.output
-
diff --git a/tests/main/interfaces-snapd-control/task.yaml b/tests/main/interfaces-snapd-control/task.yaml
--- a/tests/main/interfaces-snapd-control/task.yaml
+++ b/tests/main/interfaces-snapd-control/task.yaml
@@ -18,25 +18,38 @@ prepare: |
     echo "Given a snap declaring a plug on the snapd-control interface is installed"
     snap install --edge test-snapd-control-consumer
 
+restore: |
+    rm -f snapd.error
+
 execute: |
-    echo "The interface is connected by default"
-    snap interfaces -i snapd-control | MATCH ":snapd-control .*test-snapd-control-consumer"
+    CONNECTED_PATTERN=":snapd-control +test-snapd-control-consumer"
+    DISCONNECTED_PATTERN="(?s).*?\n- +test-snapd-control-consumer:snapd-control"
+
+    echo "Then it is connected by default"
+    snap interfaces | grep -Pzq "$CONNECTED_PATTERN"
+
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "================================================"
+
+        echo "When the plug is disconnected"
+        snap disconnect test-snapd-control-consumer:snapd-control
+        snap interfaces | grep -Pzq "$DISCONNECTED_PATTERN"
+
+        echo "Then the snap command is not able to control snapd"
+        if test-snapd-control-consumer.list 2>snapd.error; then
+            echo "Expected error with plug disconnected"
+            exit 1
+        fi
+        grep -q "Permission denied" snapd.error
+    fi
+
+    echo "================================================"
+
+    echo "When the plug is connected"
+    snap connect test-snapd-control-consumer:snapd-control
+    snap interfaces | grep -Pzq "$CONNECTED_PATTERN"
 
     echo "Then the snap command is able to control snapd"
-    test-snapd-control-consumer.list | not grep -q test-snapd-tools
+    ! test-snapd-control-consumer.list | grep -q test-snapd-tools
     test-snapd-control-consumer.install test-snapd-tools
     while ! test-snapd-control-consumer.list | grep -q test-snapd-tools; do sleep 1; done
-
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
-
-    echo "When the plug is disconnected"
-    snap disconnect test-snapd-control-consumer:snapd-control
-
-    echo "Then the snap command is not able to control snapd"
-    if test-snapd-control-consumer.list 2> snapd.error; then
-        echo "Expected error with plug disconnected"
-        exit 1
-    fi
-    grep -q "Permission denied" snapd.error
diff --git a/tests/main/interfaces-system-observe/task.yaml b/tests/main/interfaces-system-observe/task.yaml
--- a/tests/main/interfaces-system-observe/task.yaml
+++ b/tests/main/interfaces-system-observe/task.yaml
@@ -1,8 +1,5 @@
 summary: Ensures that the system-observe interface works.
 
-# on s390x we do not have a serial port to observe
-systems: [-ubuntu-*-s390x]
-
 details: |
     A snap declaring the system-observe plug is defined, its command
     just calls ps -ax.
@@ -21,16 +18,23 @@ prepare: |
     fi
 
 restore: |
+    rm -f *.error
     if [[ "$SPREAD_SYSTEM" != ubuntu-14.04-* ]]; then
         systemctl stop systemd-hostnamed
     fi
 
 execute: |
-    echo "The interface is disconnected by default"
-    snap interfaces -i system-observe | MATCH -- '^- +test-snapd-system-observe-consumer:system-observe'
+    CONNECTED_PATTERN=":system-observe +test-snapd-system-observe-consumer"
+    DISCONNECTED_PATTERN="^\- +test-snapd-system-observe-consumer:system-observe"
 
-    echo "When the interface is connected"
+    echo "Then the plug is shown as disconnected"
+    snap interfaces | MATCH "$DISCONNECTED_PATTERN"
+
+    echo "==========================================="
+
+    echo "When the plug is connected"
     snap connect test-snapd-system-observe-consumer:system-observe
+    snap interfaces | MATCH "$CONNECTED_PATTERN"
 
     echo "Then the snap is able to get system information"
     expected="/dev/tty.*?serial"
@@ -42,29 +46,26 @@ execute: |
         su -l -c "test-snapd-system-observe-consumer.dbus-introspect" test | MATCH "$expected"
     fi
 
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "==========================================="
 
-    echo "And the policy has the ptrace suppression rule"
-    MATCH '^deny ptrace \(trace\),' < /var/lib/snapd/apparmor/profiles/snap.test-snapd-system-observe-consumer.consumer
+        echo "When the plug is disconnected"
+        snap disconnect test-snapd-system-observe-consumer:system-observe
+        snap interfaces | MATCH "$DISCONNECTED_PATTERN"
 
-    echo "When the plug is disconnected"
-    snap disconnect test-snapd-system-observe-consumer:system-observe
-
-    echo "Then the snap is not able to get system information"
-    if su -l -c "test-snapd-system-observe-consumer.consumer" test 2> consumer.error; then
-        echo "Expected error with plug disconnected"
-        exit 1
-    fi
-    MATCH "Permission denied" < consumer.error
-
-    if [[ "$SPREAD_SYSTEM" != ubuntu-14.04-* ]]; then
-        echo "And the snap is not able to introspect hostname1"
-        if su -l -c "test-snapd-system-observe-consumer.dbus-introspect" test 2> introspect.error; then
+        echo "Then the snap is not able to get system information"
+        if su -l -c "test-snapd-system-observe-consumer.consumer 2>${PWD}/consumer.error" test; then
             echo "Expected error with plug disconnected"
             exit 1
         fi
-        MATCH "Permission denied" < introspect.error
-    fi
+        cat consumer.error | MATCH "Permission denied"
 
+        if [[ "$SPREAD_SYSTEM" != ubuntu-14.04-* ]]; then
+            echo "And the snap is not able to introspect hostname1"
+            if su -l -c "test-snapd-system-observe-consumer.dbus-introspect 2>${PWD}/introspect.error" test; then
+                echo "Expected error with plug disconnected"
+                exit 1
+            fi
+            cat introspect.error | MATCH "Permission denied"
+        fi
+    fi
diff --git a/tests/main/interfaces-timezone-control/task.yaml b/tests/main/interfaces-timezone-control/task.yaml
--- a/tests/main/interfaces-timezone-control/task.yaml
+++ b/tests/main/interfaces-timezone-control/task.yaml
@@ -5,8 +5,7 @@ details: |
     can access timezone information and update it.
 
 prepare: |
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB"/snaps.sh
+    . $TESTSLIB/snaps.sh
 
     # Install a snap declaring a plug on timezone-control
     install_local test-snapd-timedate-control-consumer
@@ -14,15 +13,21 @@ prepare: |
 restore: |
     # Restore the initial timezone
     if [ -f timezone.txt ]; then
-        timedatectl set-timezone "$(cat timezone.txt)" || true
+        timedatectl set-timezone "$(cat timezone.txt)"
+        rm -f timezone.txt
     fi
+    rm -f call.error
 
 execute: |
-    echo "The interface is disconnected by default"
-    snap interfaces -i timezone-control | MATCH -- '^- +test-snapd-timedate-control-consumer:timezone-control'
+    CONNECTED_PATTERN=":timezone-control +test-snapd-timedate-control-consumer"
+    DISCONNECTED_PATTERN="\- +test-snapd-timedate-control-consumer:timezone-control"
 
-    echo "When the interface is connected"
+    # Check the interface is disconnected by detault
+    snap interfaces | MATCH "$DISCONNECTED_PATTERN"
+
+    # Connect the interfaces for both snaps
     snap connect test-snapd-timedate-control-consumer:timezone-control
+    snap interfaces | MATCH "$CONNECTED_PATTERN"
 
     # Read timezones information should be allowed
     timezone1=$(test-snapd-timedate-control-consumer.timedatectl-timezone list-timezones | sed -n 1p)
@@ -37,22 +42,22 @@ execute: |
     fi
 
     # Set the timezone1 as timezone and check the status
-    test-snapd-timedate-control-consumer.timedatectl-timezone set-timezone "$timezone1"
+    # The set-timezone command works but fails in some images (lp: #1650688)
+    test-snapd-timedate-control-consumer.timedatectl-timezone set-timezone $timezone1 || true
     [ "$(test-snapd-timedate-control-consumer.timedatectl-timezone status | grep -oP 'Time zone: \K(.*)(?= \()')" = "$timezone1" ]
 
     # Set the timezone2 as timezone and check the status
-    test-snapd-timedate-control-consumer.timedatectl-timezone set-timezone "$timezone2"
+    # The set-timezone command works but fails in some images (lp: #1650688)
+    test-snapd-timedate-control-consumer.timedatectl-timezone set-timezone $timezone2 || true
     [ "$(test-snapd-timedate-control-consumer.timedatectl-timezone status | grep -oP 'Time zone: \K(.*)(?= \()')" = "$timezone2" ]
 
     if [ "$(snap debug confinement)" = partial ] ; then
         exit 0
     fi
 
-    echo "When the plug is disconnected"
+    # Disconnect the interface and check access to timedatectl status
     snap disconnect test-snapd-timedate-control-consumer:timezone-control
-
-    echo "The timedatectl status cannot be retrieved"
-    if test-snapd-timedate-control-consumer.timedatectl-timezone status 2> call.error; then
+    if test-snapd-timedate-control-consumer.timedatectl-timezone status 2>${PWD}/call.error; then
         echo "Expected permission error calling timedatectl status with disconnected plug"
         exit 1
     fi
diff --git a/tests/main/interfaces-upower-observe/task.yaml b/tests/main/interfaces-upower-observe/task.yaml
--- a/tests/main/interfaces-upower-observe/task.yaml
+++ b/tests/main/interfaces-upower-observe/task.yaml
@@ -1,5 +1,11 @@
 summary: Ensure that the upower-observe interface works.
 
+systems:
+    # ppc64el disabled because of https://github.com/snapcore/snapd/issues/2504
+    - -ubuntu-*-ppc64el
+    - -fedora-*
+    - -opensuse-*
+
 details: |
     The upower-observe interface allows a snap to query UPower for power devices, history
     and statistics.
@@ -10,24 +16,23 @@ details: |
     The test uses a snap wrapping the upower command line utility, and checks that it can query
     it without error while the plug is connected.
 
-# ppc64el disabled because of https://github.com/snapcore/snapd/issues/2504
-systems:
-    - -ubuntu-*-ppc64el
-    - -fedora-*
-    - -opensuse-*
-    - -arch-*
-    - -amazon-*
-    - -centos-*
-
 prepare: |
     echo "Given a snap declaring a plug on the upower-observe interface is installed"
     snap install --edge test-snapd-upower-observe-consumer
 
-    # shellcheck source=tests/lib/systems.sh
-    . "$TESTSLIB/systems.sh"
-    if is_core_system; then
+    if [[ "$SPREAD_SYSTEM" = ubuntu-core-* ]]; then
         echo "And a snap providing a upower-observe slot is installed"
-        snap install test-snapd-upower --edge
+        snap install upower
+    else
+        . "$TESTSLIB/pkgdb.sh"
+        distro_install_package upower
+    fi
+
+restore: |
+    rm -f upower.error
+    if [[ "$SPREAD_SYSTEM" != ubuntu-core-* ]]; then
+        . "$TESTSLIB/pkgdb.sh"
+        distro_purge_package upower
     fi
 
 execute: |
@@ -38,28 +43,32 @@ execute: |
         SLOT_NAME=service
     fi
 
-    echo "The interface is connected by default"
-    snap interfaces -i upower-observe | MATCH "$SLOT_PROVIDER:$SLOT_NAME .*test-snapd-upower-observe-consumer"
+    CONNECTED_PATTERN="$SLOT_PROVIDER:$SLOT_NAME +test-snapd-upower-observe-consumer"
+    DISCONNECTED_PATTERN="\- +test-snapd-upower-observe-consumer:upower-observe"
+
+    echo "The snap is connected by default"
+    snap interfaces | MATCH "$CONNECTED_PATTERN"
 
     echo "When the plug is connected the snap is able to dump info about the upower devices"
     expected="/org/freedesktop/UPower/devices/DisplayDevice.*"
-    for _ in $(seq 20); do
+    for i in $(seq 20); do
         if ! test-snapd-upower-observe-consumer.upower --dump | MATCH "$expected"; then
             sleep 1
         fi
     done
     test-snapd-upower-observe-consumer.upower --dump | MATCH "$expected"
 
-    if [ "$(snap debug confinement)" = partial ] ; then
-        exit 0
-    fi
+    echo "==================================="
 
-    echo "When the plug is disconnected"
-    snap disconnect test-snapd-upower-observe-consumer:upower-observe
+    if [ "$(snap debug confinement)" = strict ] ; then
+        echo "When the plug is disconnected"
+        snap disconnect test-snapd-upower-observe-consumer:upower-observe
+        snap interfaces | MATCH "$DISCONNECTED_PATTERN"
 
-    echo "Then the snap is not able to dump info about the upower devices"
-    if test-snapd-upower-observe-consumer.upower --dump 2> upower.error; then
-        echo "Expected permission error accessing upower info with disconnected plug"
-        exit 1
+        echo "Then the snap is not able to dump info about the upower devices"
+        if test-snapd-upower-observe-consumer.upower --dump 2>${PWD}/upower.error; then
+            echo "Expected permission error accessing upower info with disconnected plug"
+            exit 1
+        fi
+        cat upower.error | MATCH "Permission denied"
     fi
-    MATCH "Permission denied" < upower.error
diff --git a/tests/main/snap-run/task.yaml b/tests/main/snap-run/task.yaml
--- a/tests/main/snap-run/task.yaml
+++ b/tests/main/snap-run/task.yaml
@@ -1,30 +1,19 @@
 summary: Check that `snap run` runs
 
-# strace does not support _newselect on s390x
-# (https://github.com/strace/strace/issues/57)
-systems: [-*-s390x]
-
 prepare: |
-    #shellcheck source=tests/lib/snaps.sh
-    . "$TESTSLIB"/snaps.sh
+    . $TESTSLIB/snaps.sh
     install_local basic-run
-    install_local test-snapd-sh
+    install_local test-snapd-tools
 
-debug: |
-    if [ -f stderr ]; then
-        cat stderr
-    fi
+restore: |
+    rm -f stdout stderr
+    
+debug:
+    cat stderr
 
 execute: |
     echo "Test that snap run use environments"
     basic-run.echo-data | MATCH ^/var/snap
-
-    if command -v gdb; then
-       echo "Test snap run --gdb works"
-       echo "c" | snap run --gdb test-snapd-sh.sh -c 'echo hello' > stdout
-       MATCH 'Continuing.' < stdout
-       MATCH hello < stdout
-    fi
 
     # the strace on 14.04 is too old
     if grep -q 'VERSION_ID="14.04"' /etc/os-release; then
@@ -35,30 +24,12 @@ execute: |
         snap install strace-static
     fi
     # install the snap if no system strace is found
-    if ! command -v strace; then
+    if ! which strace; then
         snap install strace-static
     fi
 
-    echo "Test snap --strace invalid works"
-    if snap run --strace="invalid" test-snapd-sh.sh -c 'echo hello' 2>stderr ; then
-        echo "snap run with an invalid strace option should fail but it did not"
-        exit 1
-    fi
-    MATCH "Can't stat 'invalid': No such file or directory" < stderr
-
-    if [[ "$SPREAD_SYSTEM" == arch-* || "$SPREAD_SYSTEM" == opensuse-tumbleweed-* ]] ; then
-        # Arch linux and Opensuse tumbleweed run the mainline kernel, strace
-        # (with event filter or not) *may* randomly get stuck on the kernel
-        # side, see:
-        # - proposed patch: https://lore.kernel.org/patchwork/patch/719314/
-        # - snap-exec & strace stuck: https://paste.ubuntu.com/p/8nVzj8Sqfq/
-        echo "SKIP further tests due to know kernel/strace problems"
-        exit 0
-    fi
-    # XXX: any tests that execute strace should be added below this point
-
     echo "Test snap run --strace"
-    snap run --strace test-snapd-sh.sh -c 'echo hello-world' >stdout 2>stderr
+    snap run --strace test-snapd-tools.echo "hello-world" >stdout 2>stderr
     MATCH hello-world < stdout
     MATCH 'write\(1, \"hello-world\\n\",' < stderr
     if grep "snap-confine" stderr; then
@@ -68,12 +39,21 @@ execute: |
     fi
 
     echo "Test snap run --strace with options works"
-    snap run --strace="-V" test-snapd-sh.sh -c 'echo hello-world' >stdout 2>stderr
-    MATCH "strace -- version" < stdout
-    [ ! -s stderr ]
+    snap run --strace="-tt" test-snapd-tools.echo "hello-world" >stdout 2>stderr
+    MATCH hello-world < stdout
+    MATCH '[0-9:.]+ write\(1, "hello-world\\n"' < stderr
+    
+    echo "Test snap --strace invalid works"
+    if snap run --strace="invalid" test-snapd-tools.echo hello 2>stderr ; then
+        echo "snap run with an invalid strace option should fail but it did not"
+        exit 1
+    fi
+    MATCH "Can't stat 'invalid': No such file or directory" < stderr
 
-    snap run --trace-exec test-snapd-sh.sh -c 'echo hello' 2> stderr
-    MATCH "Slowest [0-9]+ exec calls during snap run" < stderr
-    MATCH "  [0-9.]+s .*/snap-exec" < stderr
-    MATCH "  [0-9.]+s .*/snap-confine" < stderr
-    MATCH "Total time: [0-9.]+s" < stderr
+    if which gdb; then
+       echo "Test snap run --gdb works"
+       echo "c" | snap run --gdb test-snapd-tools.echo hello > stdout
+       cat stdout | MATCH 'Continuing.'
+       cat stdout | MATCH hello
+    fi
+
